FROM python:3.10-alpine

RUN apk add --no-cache build-base linux-headers gfortran openblas-dev

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "spaceship.main:app", "--host", "0.0.0.0", "--port", "8000"]